### ISSUE TITLE
[feature] Support scoped targets in `deps`

### ISSUE THREAD

**Issue by milesj** [milesj/moon#49]
**Is your feature request related to a problem? Please describe.**

No, new feature.

**Describe the solution you'd like**

Currently the task's `deps` field accepts a list of targets, in the format of "project:task". While this works, it can be quite tedious to explicitly list out all project dependencies for every task. To work around this, the following values can be used _instead_ of project names, to auto-fill multiple values.

- `^:<task>` - Will mark all project dependencies (`dependsOn` in `project.yml`) as task `deps`, if they have a task with the name `<task>`.

```yaml
tasks:
  build:
    command: 'webpack'
    args:
      - 'bundle'
    deps:
      - '^:build'
      # Instead of 
      - 'foo:build'
      - 'bar:build'
      - 'baz:build'
```

- `~:<task>` - Will reference a task named `<task>` within itself/the owning project. This is a shortcut for using the own project's name in `deps`.

```yaml
tasks:
  build:
    command: 'jest'
    deps:
      - '~:build'
      # Instead of 
      - 'self:build'
```

**Describe alternatives you've considered**

N/A

**Additional context**
